<?php session_start()?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 4</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>

    </style>
</head>
<body>
<h1>SLim BoyZ Auto Cover</h1>
<h2>Quotes for <?= $name ?></h2>
<?= \SlimAutoCover\Viewhelpers\QuotesViewHelper::FormRender(isset($_SESSION['quotes']) ? $_SESSION['quotes'] : $quotes, isset($_SESSION['name']) ? $_SESSION['name'] : $name) ?>
</body>
</html>